apiVersion: apps/v1
kind: Deployment
metadata:
  name: advanced-search-app
  namespace: commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advanced-search-app
  template:
    metadata:
      labels:
        app: advanced-search-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: advanced-search-app
          image: advanced-search-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_ELASTICSEARCH_URIS
              value: "http://elasticsearch.commerce-search.svc.cluster.local:9200"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30